module.exports = {
    REQUEST_PRESIDENTS: 'REQUEST_PRESIDENTS',
    RECEIVE_PRESIDENTS: 'RECEIVE_PRESIDENTS',
    REQUEST_PRESIDENTS_ORDERED: 'REQUEST_PRESIDENTS_ORDERED',
    RECEIVE_PRESIDENTS_ORDERED: 'RECEIVE_PRESIDENTS_ORDERED'
};